### ISSUE TITLE
lifecycle postStart hook may run before the service starts

### ISSUE THREAD

**Issue by liangjs** [otwld/ollama-helm#100]
### What happened?

Kubernetes sends the postStart event immediately after a Container is started, so the postStart command may run even before the service is ready.
Pulling models before `ollama serve` will result in an error:
```
Error: could not connect to ollama app, is it running?
```

### Chart version

0.58.0

### Kubernetes version

1.27.16

### Kubernetes distribution

k8s

**Comment by jdetroyes** [comment]
Hi @liangjs 

Thanks for the issue, we will add a "loop check" to ensure Ollama is running before pulling models.
