### ISSUE TITLE
Default updateStrategy to Recreate

### ISSUE THREAD

**Issue by RomLecat** [otwld/ollama-helm#104]
### What happened?

The Helm default values is updateStrategy to RollingUpdate, and persistentVolume accessModes to ReadWriteOnce.

This causes the upgrades to fail with the new revisions stuck in ContainerCreating state, since they're waiting on the PVC being free, which will never be because the pod of the previous revision is waiting on the pod of the newest revision to be up. This is a deadlock scenario with default value (with persistence enabled, which is, granted, not default).

I still think that updateStrategy should be "Recreate" by default, since ReadWriteMany PVCs are not always possible.

### Chart version

0.60.0

### Kubernetes version

1.28.12

### Kubernetes distribution

k8s

### Your values.yaml

```yaml
persistentVolume:
  enabled: true
```

**Comment by jdetroyes** [comment]
Hello @RomLecat

Good catch!

We will modify the default value to Recreate.

**Comment by jdetroyes** [comment]
Fixed in `0.61.0`
