### ISSUE TITLE
0.66.0 not propogated to helm repo or artifacthub

### ISSUE THREAD

**Issue by graemes** [otwld/ollama-helm#117]
### What happened?

Updated using `helm repo update` and then add `--version 0.66.0` to my helm update command.

Received this error:
`Error: chart "ollama" matching 0.66.0 not found in ollama-helm index. (try 'helm repo update'): no chart version found for ollama-0.66.0`

On ArtifactHub Application Versionis 0.4.1 and Chart Version 0.65.0

### Chart version

0.66.0

### Kubernetes version

1.30

### Kubernetes distribution

RKE2

### Relevant log output

```shell
Error: chart "ollama" matching 0.66.0 not found in ollama-helm index. (try 'helm repo update'): no chart version found for ollama-0.66.0
```

**Comment by jdetroyes** [comment]
Hello @graemes 

The index was not updated on the helm repository. It's now fixed and it will be update by artifacthub in maximum 30 minutes.
