### ISSUE TITLE
Auto load model

### ISSUE THREAD

**Issue by NigelVanHattum** [otwld/ollama-helm#119]
### Is your feature request related to a problem? Please describe

With the current setup of Ollama I need to exec into one of the pods on my cluster to load a model. With the dynamic scaling of my cluster it's hard to keep a model loaded at all times. 

### Describe the solution you'd like

An extra parameter that is able to load a specific list of models directly after the start of the pod. 

### Describe alternatives you've considered

Manually loading the model each time

**Comment by jdetroyes** [comment]
Hello @NigelVanHattum 

We will add an extra key value to run models at startup as `ollama run` command.

**Comment by jdetroyes** [comment]
It will be available in next release.
