### ISSUE TITLE
Ollama not responding to text

### ISSUE THREAD

**Issue by Yabbo** [otwld/ollama-helm#16]
I have it deployed into my kubernetes cluster on a GPU node with an RTX 2080 Ti (ollama runs a  container on this node with no issues) its able to pull down models but when i sent it a question it doesnt respond.

My vales.yaml 

`ollama:`
 ` gpu:`
    # -- Enable GPU integration
`    enabled: true`
    # -- Specify the number of GPU to 2
`    number: 1`

`service:`
`  ports:`
`    port: 11434`
`    targetPort: 11434`
`  type: LoadBalancer`

`persistentVolume:`
`  enabled: true`
`  storageClass: ""`

Kubernetes Version: v1.26.8 +rke2r1

even though its pulling to a gpu node and mapping to the gpu its not using the gpu when i do get it to respond. I dont see it using the gpu in nvtop

**Comment by jdetroyes** [comment]
Hello @Yabbo,

Can you past the logs of the container?

**Comment by Yabbo** [comment]
i had to reboot the kubernetes node and then it was able to respond. not sure what happened. ill close this out.
