### ISSUE TITLE
Ollama performance very bad

### ISSUE THREAD

**Issue by Tim-herbie** [otwld/ollama-helm#20]
Hello,

I installed the ollama helm chart on my Kubernetes Cluster with the llama2 module.

It worked, but the performance is very bad. I added also the webui and it's really pretty cool, but with the current speed I can't use it.

I testet it with 6 CPU and 24GB Ram, but it didn't get faster.

Did I something wrong or is there another module that is faster? I don't have a good GPU on my Kubernetes servers, so I can't really use that.

I installed ollama also locally on my M1 Mac and the performance there was much faster.

**Comment by jdetroyes** [comment]
Hello @Tim-herbie 

The performance of ollama depends on the hardware, models until 7B can run on CPU. 

Performance with apple M chips are better than CPU due to the Shared Unified Memory. 

Unfortunately, to enjoy models with good performance GPU is recommended with dedicated VRAM.
