### ISSUE TITLE
How to use a custom offline models

### ISSUE THREAD

**Issue by praveen-kanamarlapudi** [otwld/ollama-helm#25]
Hi Team,

I have a fine-tuned model based on mixtral in our env (S3, local). How can I use it with ollama helm charts?

Thanks

**Comment by jdetroyes** [comment]
Hello @praveen-kanamarlapudi,

You can use the [REST API](https://github.com/ollama/ollama/blob/main/docs/api.md#push-a-model) to push a model from your local ollama to the remote ollama. 

```curl
curl https://<REMOTE-OLLAMA-URL:PORT_IF_NEEDED>/api/push -d '{
  "name": "<LOCAL-MODEL>:<TAG>"
}'
```

**Comment by praveen-kanamarlapudi** [comment]
Is it possible to automate it? May be build the docker image with my model to automate the process?

**Comment by jdetroyes** [comment]
One solution but not tested, may be to use [OCI Artifacts registries](https://github.com/opencontainers/distribution-spec) for store ollama's images on s3.

According to [this issue](https://github.com/ollama/ollama/issues/2745#issuecomment-1972323644) and using a managed OCI like [AWS ECR with OCI](https://aws.amazon.com/blogs/containers/oci-artifact-support-in-amazon-ecr/), you will be able to pull models from external registries.

You can use a lambda function with a trigger when a new artefact is pushed to OCI to call the API:

```
curl https://<REMOTE-OLLAMA-URL:PORT_IF_NEEDED>/api/push -d '{
  "name": "<host>/<namespace>/<repo>:<tag>"
}'
```

And if you want to pull an image at startup:

```yaml
ollama:
  models:
    - <host>/<namespace>/<repo>:<tag>
```

**Comment by ericcurtin** [comment]
https://github.com/llmmanorg/llmman does this FWIW push/pull to OCI registry and/or huggingface registry
