### ISSUE TITLE
Can't render deployment template when i wanna enable GPU flag

### ISSUE THREAD

**Issue by thinking-and-coding** [otwld/ollama-helm#4]
These are error messages:

`Failed to get upgrade info: template: ollama/templates/deployment.yaml:56:89: executing "ollama/templates/deployment.yaml" at <.Values.ollama.gpu.nbrGpu>: nbrGpu is not a method but has arguments`

**Comment by jdetroyes** [comment]
Hello @thinking-and-coding,

This error will be fix in the next release today, the old variable "nbrGpu" has been deleted.

Thanks you!
