### ISSUE TITLE
Integrate Knative Support

### ISSUE THREAD

**Issue by llorenzinho** [otwld/ollama-helm#42]
It would be great to have the chance to use knative to deploy the ollama chart in order to scale down to zero the number of pods and even the gpu nodes when no one is using the LLM (money saving).

**Comment by ntrehout** [comment]
@llorenzinho 

I've submitted a pull request to address your request. While I'm relatively new to Knative, I've tested it on a local cluster and confirmed functionality. However, given my limited experience with Knative, your guidance and support in reviewing the changes would be immensely valuable. Thank you for your understanding and assistance!
