### ISSUE TITLE
Knative Use question

### ISSUE THREAD

**Issue by skonto** [otwld/ollama-helm#60]
Hi folks! I am a Knative maintainer. Saw the integration here: https://github.com/otwld/ollama-helm/pull/43.
I am wondering if  you are using Knative for ollama deployment in practice.

**Comment by ntrehout** [comment]
Hi there! Thanks for reaching out. Currently, we're not utilizing Knative for ollama in practice. 

However, if you have any specific issues or suggestions, we'd definitely welcome a pull request (PR). 

Let us know how we can collaborate!

Feel free to join the [discord ](https://discord.gg/psdtZ4yG) to discuss about it :)

Have a nice day !
