### ISSUE TITLE
how to load custom model in local directory into openwebui

### ISSUE THREAD

**Issue by kzos** [otwld/ollama-helm#62]
`ollama create myllama -f Modelfile `==> could generate the model file
`ollama list `and `ollama run myllama` works find in cli.

but issue comes when using openwebui with below command.

`docker run -d -p 3000:8080 --gpus=all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama`

![Screenshot from 2024-07-07 17-16-15](https://github.com/otwld/ollama-helm/assets/5010954/8c485197-8fae-47e3-9e7a-7ff19fc2c1f8)

As its expecting manifest at ollama.com
how do i point the server to load it from local while instantiating docker (or idk where to do this setting).

please help

Note: Worst case if i want to push to ollama.com using curl push

`curl http://localhost:11434/api/push -d '{^J"name": "myllama:latest"^J}' `

I get error
`time=2024-07-07T09:50:27.930-04:00 level=INFO source=images.go:795 msg="error uploading blob: 400: {\"errors\":[{\"code\":\"ACCESS_DENIED\",\"message\":\"access denied\"}]}"`

but pushing is secondary, 
first thing would be to load from local directory without pushing to ollama.com

**Comment by jdetroyes** [comment]
@kzos 

Can you check the Ollama API URL entered in Open WebUI?

Admin Panel > Settings > Ollama API
