### ISSUE TITLE
[Feature] Topology Spread Constraints via Helm Chart Values

### ISSUE THREAD

**Issue by Enorshionari** [otwld/ollama-helm#83]
### Is your feature request related to a problem? Please describe

Currently there are no options to spread ollama pods on cluster without setting resource requests/limits. Two pods could be allocated on same node.

### Describe the solution you'd like

Adding topologySpreadConstraints options on helm chart values could solve that issue.

**Comment by jdetroyes** [comment]
Hi @Enorshionari 

Thanks you for this feature request, we will update the chart to include topologySpreadConstraints.

**Comment by jdetroyes** [comment]
Added in `0.51.0`
