### ISSUE TITLE
How to Deploy Ollama LLM on Cloud-Managed Kubernetes (OCI) (pvc/init container)

### ISSUE THREAD

**Issue by brokedba** [otwld/ollama-helm#90]
### How to Deploy Ollama LLM on Cloud-Managed Kubernetes (OCI)

I'm looking for guidance on deploying Ollama LLM using Helm charts on a cloud-managed Kubernetes service, specifically Oracle Cloud Infrastructure (OCI). I have a few questions regarding the deployment process:

1. **Persistent Volume and Data Volume Mounting**:
   - From the values in the Helm chart, how does the `ollama-data` volume `mountPath: ""` match the `persistentVolume` if it's enabled? It's unclear how these values are connected.
   - Do we need to create the storage class or PersistentVolumeClaim (PVC) manually for the `persistentVolume.values` to be effective? There isn't much clarity on this in the documentation, and it would be helpful to have an example.

2. **Loading Models with Init Containers**:
   - Is there a way to load the models using an init container into the `mountPath` before the main pod is spun up? This feature would be useful for preloading models and ensuring they're ready when the main container starts.

The documentation seems limited, making it challenging to proceed. Any examples or additional guidance would be greatly appreciated.
Thank you

**Comment by brokedba** [comment]
@jdetroyes thank you so much for the answers !!
> First, if ollama.mountPath is set, it overrides the default mount path of /root/.ollama. In most cases, this value doesn't need to be changed. When persistentVolume is enabled, there are two scenarios:
> - If persistentVolume.existingClaim is set:
The volume will be attached to the container.
> - If persistentVolume.existingClaim is not set:
> - If persistentVolume.storageClass is specified (or left empty), a PVC will be created by the provisioner and attached to the container (See pvc.yaml).
>
> You can specify a StorageClass that is already configured in your infrastructure to automatically create a PVC. Alternatively, if you already have a PVC configured, you can set the persistentVolume.existingClaim field. To disable automatic provisioning, set persistentVolume.storageClassName: "-".
  
  
  If  I understand well , `ollama.mountPath` matches either:
  1. The existing claim if specified 
  2. Else a new one that is created by the chart through dynamic provisioning by the storageClass
  
  but if StorageClass doesn't exist , the option 2 will not really work am I right . 
  for now I tried creating local PV and pvc and specified the existing claim but I had below error
  
  ```
  
  ```

**Comment by brokedba** [comment]
I hit  Docker Hub rate limits so I needed to add dockerhub  secret but it's complaining .

>W0829 17:43:50.092448    9912 warnings.go:70] unknown field "spec.template.spec.initContainers[0].imagePullSecrets"
Release "ollama" has been upgraded. Happy Helming!

am I missing something ? is it included in the template ?
```
initContainers:
  - name: install-and-setup-model
    image: python:3.9  # Use an image with Python and pip pre-installed
    imagePullSecrets:
      - name: dockerhub-sec
    command: [sh, -c]
    args:
  ```

**Comment by jdetroyes** [comment]
Hey @brokedba 

Docker secrets are shared with all containers in the deployment. 

You don't have to add a line in the initContainers, you just have to populate in the values.yaml 

`# -- Docker registry secret names as an array
imagePullSecrets: []`

**Comment by brokedba** [comment]
my bad I had corrected   before I could update the post.
the container is still in pending mode now after that change 

```
Events:                                                                                                                                                                                            │
│   Type     Reason            Age                    From               Message                                                                                                                     │
│   ----     ------            ----                   ----               -------                                                                                                                     │
│   Warning  FailedScheduling  9m32s                  default-scheduler  0/3 nodes are available: persistentvolumeclaim "ollama" is being deleted. preemption: 0/3 nodes are available: 3 Preemption │
│  is not helpful for scheduling.                                                                                                                                                                    
││   Warning  FailedScheduling  4m59s (x3 over 9m14s)  default-scheduler  0/3 nodes are available: persistentvolumeclaim "ollama" not found. preemption: 0/3 nodes are available: 3 
Preemption is not  helpful for scheduling.               
```

**Comment by brokedba** [comment]
I also noted that the result of the modelfile is truncated  where any line between {{}}} was ignored .
Although the echo or printf commands works manually after the pod is ready. 

the below is the final version after I logged in to the container.  
```
FROM /root/.ollama/download/Meta-Llama-3.1-8B-Instruct-Q4_K_S.gguf

# Set custom parameter values
PARAMETER temperature 1.0
PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|end_header_id|>"
PARAMETER stop "<|eot_id|>"

# Define the model template
TEMPLATE """<|start_header_id|>assistant<|end_header_id|>       <------lines below were all ignored
<|eot_id|>
"""

# Set the system message
SYSTEM You are a helpful AI assistant named e-llmo Assistant. 

```
