### ISSUE TITLE
Prioritity queuing

### ISSUE THREAD

**Issue by JBleher** [otwld/ollama-helm#91]
### Is your feature request related to a problem? Please describe

We want to submit to ollama requests for a ChatBot use and for automated labeling. The automated labeling sends request all the time. If we do not have a priority queue the users of the ChatBot will need to wait a long time for their answer. The labeling however, is not time sensitive. I.e. the chat users should be served first and immediately.

### Describe the solution you'd like

A system that prioritizes the requests depending on the priority the ChatBot user choses in his/her payload.

**Comment by jdetroyes** [comment]
Hello @JBleher 

Your feature request seems related to message queue as external service, you can take a look to message broker like [rabbitmq](https://www.rabbitmq.com/) or [kafka](https://kafka.apache.org/).

Can you provides more details if you consider this is achievable only using Kubernetes.
